KanakaTicketBookingApp/Controllers/BusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KanakaTicketBookingApp.Domain;
using KanakaTicketBookingApp.Repository;
using KanakaTicketBookingApp.VO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace KanakaTicketBookingApp.Controllers
{
    public class BusController : Controller
    {
        private readonly IBusRepository busRepository;
        private readonly ILogger<BusController> logger;

        public BusController(IBusRepository busRepository, ILogger<BusController> logger)
        {
            this.busRepository = busRepository;
            this.logger = logger;
        }
        [HttpGet]
        public IActionResult Index()
        {
            logger.LogInformation("Index started");

            var busesVO = busRepository.GetAllBuses().Select<Bus, BusVO>(bus => new BusVO()
            {
                Id = bus.Id,
                Name=bus.Name,
                Number = bus.Number
            });
            logger.LogInformation("Index ended");

            return View(busesVO);
        }

        [HttpGet]
        public IActionResult AddBus()
        {
            logger.LogInformation(" AddBus started");
            logger.LogInformation(" AddBus ended");

            return View();
        }

        [HttpPost]
        public IActionResult AddBus(AddBusVO addBusVO)
        {
            logger.LogInformation("AddBus started", addBusVO);

            if (ModelState.IsValid)
            {
                Bus bus = new Bus()
                {
                    Name = addBusVO.Name,
                    Number = addBusVO.Number
                };

                busRepository.AddBus(bus);
                logger.LogInformation("AddBus ended");
                return RedirectToAction("Index");
            }
            logger.LogInformation("AddBus ended");

            return View(addBusVO);
        }


    }
}

KanakaTicketBookingApp/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KanakaTicketBookingApp.Domain;
using KanakaTicketBookingApp.Repository;
using KanakaTicketBookingApp.VO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace KanakaTicketBookingApp.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventRepository eventRepository;
        private readonly IBusRepository busRepository;
        private readonly ILogger<EventController> logger;

        public EventController(IEventRepository eventRepository, 
                                IBusRepository busRepository, 
                                ILogger<EventController> logger)
        {
            this.eventRepository = eventRepository;
            this.busRepository = busRepository;
            this.logger = logger;
        }
        public IActionResult Index()
        {
            logger.LogInformation("Index started");

            var r = eventRepository.GetAllEvents();

            var eventsVO = eventRepository.GetAllEvents().Select<Event, EventVO>(_event =>
            new EventVO()
            {
                Id = _event.Id,
                StartPoint = _event.StartPoint,
                EndPoint = _event.EndPoint,
                Date = _event.Date,
                
                BusVO = new BusVO()
                {
                    Id = _event.Bus.Id,
                    Name = _event.Bus.Name,
                    Number = _event.Bus.Number
                }
            });
            logger.LogInformation("Index ended");

            return View(eventsVO);
        }

        [HttpGet]
        public IActionResult AddEvent()
        {
            logger.LogInformation("AddEvent started");

            ViewBag.BusVO = busRepository.GetAllBuses().Select<Bus, BusVO>(b =>
            {
                return new BusVO()
                {
                    Id = b.Id,
                     Name = b.Name,
                     
                };
            });
            logger.LogInformation("AddEvent ended");

            return View();
        }

        [HttpPost]
        public IActionResult AddEvent(AddEventVO addEventVO)
        {
            logger.LogInformation("AddEvent started", addEventVO);

            if (ModelState.IsValid)
            {              
                var events = eventRepository.GetAllEvents();
                bool isEventPresent = false;
                foreach (var item in events)
                {                   
                    if (item.Date.CompareTo(addEventVO.Date)==0 && item.BusId == addEventVO.BusId)
                    {
                        isEventPresent = true;
                        ModelState.AddModelError("", "Event is already schedule for bus with given date");
                        break;
                    }
                }

                if (!isEventPresent) {
                    Event _event = new Event()
                    {
                        StartPoint = addEventVO.StartPoint,
                        EndPoint = addEventVO.EndPoint,
                        Date = addEventVO.Date,
                        BusId = addEventVO.BusId
                    };

                    eventRepository.AddEvent(_event);

                    logger.LogInformation("AddEvent ended");
                    return RedirectToAction("Index");
                }
            }

            ViewBag.BusVO = busRepository.GetAllBuses().Select<Bus, BusVO>(b =>
            {
                logger.LogInformation("AddEvent ended");
                return new BusVO()
                {
                    Id = b.Id,
                    Name = b.Name,

                };
            });


            logger.LogInformation("AddEvent ended");

            return View(addEventVO);
        }

    }
}

KanakaTicketBookingApp/Controllers/TicketController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KanakaTicketBookingApp.Domain;
using KanakaTicketBookingApp.Repository;
using KanakaTicketBookingApp.VO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace KanakaTicketBookingApp.Controllers
{
    public class TicketController : Controller
    {

        private readonly IEventRepository eventRepository;
        private readonly IBusRepository busRepository;
        private readonly ITicketRepository ticketRepository;
        private readonly ILogger<TicketController> logger;

        public TicketController(IEventRepository eventRepository, 
                                IBusRepository busRepository,
                                ITicketRepository ticketRepository,
                                 ILogger<TicketController> logger)
        {
            this.eventRepository = eventRepository;
            this.busRepository = busRepository;
            this.ticketRepository = ticketRepository;
            this.logger = logger;
        }

        [Authorize(Policy = "ManagerRights")]
        public IActionResult Index()
        {
            logger.LogInformation("Index started");

            var ticketsVO = ticketRepository.GetAllTickets().Select<Ticket, TicketVO>(ticket =>
            new TicketVO()
            {
                PassangerName = ticket.PassangerName,
                EventId = ticket.EventId,
                SeatNo = ticket.SeatNo,

                EventVO = new EventVO()
                {
                    StartPoint = ticket.Event.StartPoint,
                    EndPoint = ticket.Event.EndPoint,
                    Date = ticket.Event.Date,
                    BusVO = new BusVO()
                    {
                        Name = busRepository.GetById(ticket.Event.BusId).Name
        }
                }
            });


            logger.LogInformation("Index ended");

            return View(ticketsVO);
        }


        [HttpGet]
        public IActionResult BookTicket(long id)
        {
            logger.LogInformation("BookTicket started",id);


            List<bool> seatStatus = new List<bool>();


                var tickets = ticketRepository.GetTicketByEvent(id);

                for (int i = 0; i < 36; i++)
                {
                    int flag = 0;
                    foreach (var ticket in tickets)
                    {
                        if ((ticket.SeatNo - 1).Equals(i))
                        {
                            seatStatus.Add(true);
                            flag = 1;
                            break;
                        }
                    }

                    if (flag == 0)
                    {
                        seatStatus.Add(false);
                    }
                }
                var bookTicketVO = new BookTicketVO()
                {
                    EventId = id,
                    SeatNo = seatStatus
                };
            logger.LogInformation("BookTicket Ended");

            return View(bookTicketVO);
            
            
        }


        [HttpPost]
        public IActionResult BookTicket(BookTicketVO bookTicketVO)
        {
            logger.LogInformation("Bookticket started", bookTicketVO);

            if (ModelState.IsValid)
            {
                List<long> newSeatNo = new List<long>();
                for (int i = 0; i < bookTicketVO.SeatNo.Count; i++)
                {
                    if (bookTicketVO.SeatNo[i])
                    {
                        newSeatNo.Add((i + 1));
                    }
                }

                foreach (var item in ticketRepository.GetTicketByEvent(bookTicketVO.EventId))
                {
                    if (newSeatNo.Contains(item.SeatNo))
                    {
                        newSeatNo.Remove(item.SeatNo);                       
                    }
                }

                foreach (var item in newSeatNo)
                {
                    Ticket ticket = new Ticket()
                    {
                        EventId = bookTicketVO.EventId,
                        PassangerName = bookTicketVO.PassangerName,
                        SeatNo = item
                    };

                ticketRepository.AddTicket(ticket);
                }
                logger.LogInformation("Bookticket ended"); 
                return RedirectToAction("Index");


            }
            logger.LogInformation("Bookticket ended");
            return View(bookTicketVO);
        }


       
    }
}

KanakaTicketBookingApp/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;

@{
    var appName = "KanakaTicketBookingApp";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @appName</title>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-light bg-light sticky-top">

        <a class="navbar-brand" asp-controller="Home" asp-action="Index">@appName</a>

        <button data-toggle="collapse" data-target="#navMenu" class="navbar-toggler">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="navMenu">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>

                @* drop down for BUS *@
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#"
                       id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Bus
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-area="" asp-controller="Bus" asp-action="Index">Show</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-area="" asp-controller="Bus" asp-action="AddBus">Add New</a>

                    </div>
                </li>


                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Event" asp-action="Index">Event</a></li>





                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Ticket" asp-action="Index">Ticket</a></li>

            </ul>

            <ul class="navbar-nav ">




                @* dropdown for role related *@
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#"
                       id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Role
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="ManageRoles">Manage Role</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="CreateRole">Create Role</a>

                    </div>
                </li>

                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Account" asp-action="Manageclaim">Claim</a></li>




                @if (signInManager.IsSignedIn(User))
                {
                    <li class="nav-item "><p class="btn   my-sm-0">@User.Identity.Name</p></li>
                    <li class="nav-item ">
                        <form asp-controller="Account" asp-action="Logout" method="post">
                            <button type="submit" class="btn  btn-outline-dark">Logout</button>
                        </form>
                    </li>
                }
                else
                {
                    <li class="nav-item"><a class="nav-link btn  btn-outline-dark mr-2" asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                    <li class="nav-item"><a class="nav-link btn  btn-outline-dark " asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
                }
            </ul>
        </div>
    </nav>

























    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - @appName</p>
        </footer>
    </div>



    @RenderSection("Scripts", required: false)

    <script src="~/lib/jquery.slim.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/esm/popper.js"></script>

</body>
</html>